<div class="text-center">
<h2>Přidat produkt</h2>
</div>
<div class="row justify-content-center my-3">
	<div class="col-lg-6">
	<form method="post" class="needs-validation" novalidate>
		<div class="form-group mb-2">
				<label for="id"></label>
				<input type="hidden" class="form-control" name="zbozi_id">
				
			</div>
			<div class="form-group mb-2">
				<label for="nazevInput">Název</label>
				<input type="text" class="form-control" id="nazevInput" name="nazev" required>
				<div class="invalid-feedback">
        			Prosím, vyplňte jméno.
      			</div>
			</div>
			<div class="form-group mb-2">
				<label for="kategorieInput">Kategorie</label>
				<input type="text" class="form-control" id="kategorieInput" name="kategorie">
				
			</div>
			<div class="form-group mb-2">
				<label for="popisInput">Popis</label>
				<textarea class="form-control" id="popisInput" name="popis" rows="7"></textarea>
			</div>
			<div class="form-group mb-2">
				<label for="sklademInput">Skladem</label>
				<input type="text" class="form-control" id="sklademInput" name="mnozstvi_skladem" >
			</div>
			<div class="form-group mb-4">
				<label for="cenaInput">Cena</label>
				<input type="text" class="form-control" id="cenaInput" name="cena_s_DPH" required>
				<div class="invalid-feedback">
        			Prosím, vyplňte cenu s DPH.
      			</div>
			</div>
			<div class="text-center">
				<button type="submit" class="btn btn-primary">Uložit položku</button>
			</div>
			
		</form>
	</div>
</div>

<script>
	var forms = document.querySelectorAll('.needs-validation');
	
	Array.prototype.slice.call( forms ).forEach( function( form )
	{
		form.addEventListener( 'submit', function ( event )
		{
			if ( !form.checkValidity( ) )
			{
				event.preventDefault( )
				event.stopPropagation( );
			}

			form.classList.add( 'was-validated' );
	}, false );
	} );
</script>
	



