<div class="text-center">
	<h1>Registrace</h1>
</div>
<div class="row justify-content-center my-5">
    <div class="col-lg-6">
		<form method="post">
			<div class="form-group mb-2">
				<label for="jmenoInput">Uživatelské jméno</label>
				<input type="text" class="form-control" id="jmenoInput" name="uzivatelske_jmeno" placeholder="Vyplňte uživatelské jméno">
			</div>
			<div class="form-group mb-2">
				<label for="emailInput">Email</label>
				<input type="email" class="form-control" id="emailInput" name="email" placeholder="Vyplňte email">
			</div>
			<div class="form-group mb-2">
				<label for="hesloInput">Heslo</label>
				<input type="password" class="form-control" name="heslo" id="hesloInput" placeholder="Vyplňte heslo">
			</div>
			<div class="form-group mb-4">
				<label for="hesloZnovuInput">Heslo znovu</label>
				<input type="password" class="form-control" name="heslo_znovu" id="hesloZnovuInput" placeholder="Vyplňte heslo znovu">
			</div>
			<div class="text-center">
				<button type="submit" class="btn btn-primary ">Registrovat</button>
			</div>
			
		</form>
	</div>	
</div>
<div class="text-center">
	<p>Máte již účet? <a href="prihlaseni">Přihlaste se.</a></p>
</div>




