<!DOCTYPE html>
<html lang="cs-cz">
	<head>
		<base href="/localhost" />
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link 
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" 
			rel="stylesheet" 
			integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
			crossorigin="anonymous"
			/>
		<title><?= $title ?></title>
		<link rel="stylesheet" href="style.css" type="text/css" />
	</head>
	<body class="d-flex flex-column min-vh-100">
		<header>
            <nav class="navbar navbar-expand-lg bg-dark navbar-dark py-3 ">
                <div class="container">
                    <div class="navbar-brand">Inventář zboží</div>

                    <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navmenu"
                    >
                    <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navmenu">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                        <a href="inventar" class="nav-link">Inventář</a>
                        </li>
                        <li class="nav-item">
                        <a href="ucet" class="nav-link">Účet</a>
                        </li>
                    </ul>
                    </div>
                </div>
            </nav>
		</header>
		<main class="my-5">
			<div class="container">
					<!-- addMessage() -->
					<?php foreach ($messages as $message) : ?>
						<div class="alert alert-success d-flex align-items-center" role="alert">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"  viewBox="0 0 16 16" role="img" class="mx-2">
								<path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
							</svg>
							<div>
								<?= $message ?>
							</div>
						</div>
					<?php endforeach ?>

					<!-- addWarning -->
					<?php foreach ($warnings as $warning) : ?>
						<div class="alert alert-danger d-flex align-items-center" role="alert">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 16 16" role="img" class="mx-2">
							<path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
							</svg>
							<div>
								<?= $warning ?>
							</div>
						</div>
					<?php endforeach ?>
					<div class="container my-5">
						<?php $this->controller->printView(); ?>
					</div>
			</div>
		</main>
		
		<footer class="footer mt-auto py-3 bg-dark">
      		<div class="container text-center">
				<span class="text-white-50">Copyright &copy; 2022 Zbyněk Vrtal</p>
      		</div>
    	</footer>
		
		<script
		src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
		integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
		crossorigin="anonymous"
		></script>
		<script
		src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
		integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
		crossorigin="anonymous"
		></script>
	</body>
</html>